# Generated by Django 3.2.3 on 2021-06-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
    ]
