# Generated by Django 3.2.3 on 2021-06-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210614_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
            preserve_default=False,
        ),
    ]
